### ISSUE TITLE
feat(calendar-days): ngx-calendar-days

### ISSUE THREAD

**Issue by ruizalexandre** [ruizalexandre/ngx-calendar#9]
- [x] Create ngx-calendar-days
- [x] Display days like [_Sunday to Saturday_] or [_Monday to Sunday_]
- [x] Use angular locale to display days in right language

```typescript
@Input()
readonly startDay: CalendarStartDay = CalendarStartDay.Sunday;

get days() {
  return this.startDay === CalendarStartDay.Sunday 
    ? [0, 1, 2, 3, 4, 5, 6]
    : [1, 2, 3, 4, 5, 6, 0];
}
```

```scss
:host {
  display: flex;
  background-color: #ebebeb;
  height: 48px;

  .day {
    flex: 1 1 auto;
    display: flex;
    align-items: center;
    justify-content: center;
  }
}
```

**Change detection**
`changeDetection: ChangeDetectionStrategy.OnPush`

**Days pipe**
```typescript
import { Pipe, PipeTransform, Inject } from '@angular/core';
import { LOCALE_ID } from '@angular/core';
import { getLocaleDayNames, TranslationWidth, FormStyle } from '@angular/common';

@Pipe({
  name: 'days'
})
export class DaysPipe implements PipeTransform {

  constructor(
    @Inject(LOCALE_ID) public local: string
  ) {}

  transform(dayIndex: number, translationWidth: TranslationWidth): any {
    const days = getLocaleDayNames(
      this.local.slice(0, 2), 
      FormStyle.Standalone, 
      translationWidth
    );

    return days[dayIndex];
  }
}
```

**UI available here**
https://www.figma.com/file/Jk6ca2AnACP5LOojr2HRar/ngx-calendar?node-id=23%3A12
